{% set name = "cdflib" %}
{% set version = "1.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f32f679624982cbfd7677ffb8741c087071c03df5650e3148259a387b67e3110


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - astropy-base
    - xarray

test:
  imports:
    - cdflib
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - astropy-base
    - pip
    - xarray

about:
  home: https://github.com/MAVENSDC/cdflib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python CDF reader toolkit
  description: |
    A python CDF reader toolkit
  doc_url: https://cdflib.readthedocs.io/en/latest/
  dev_url: https://github.com/MAVENSDC/cdflib

extra:
  recipe-maintainers:
    - Cadair
    - Alexs12
