{% set name = "cdflib" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d4c3c26f6b5a7dfa89ec9a405fff5fcbe777885cb203953de666e1b27d75b4d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - twine >=1.11
  run:
    - astropy
    - attrs >=19.2.0
    - python >=3.5
    - numpy
    - xarray

test:
  imports:
    - cdflib
  commands:
    - pip check
  requires:
    - astropy
    - xarray

about:
  home: https://github.com/MAVENSDC/cdflib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python CDF reader toolkit
  description: |
    A python CDF reader toolkit
  doc_url: https://cdflib.readthedocs.io/en/latest/
  dev_url: https://github.com/MAVENSDC/cdflib

extra:
  recipe-maintainers:
    - dstansby
    - Alexs12
