{% set name = "cdflib" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97f27ac629e4c0ac1367eb8f4edd7a1d184190272ab98a6401e999f3a2e05687


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.21
    - astropy
    - xarray

test:
  imports:
    - cdflib
  commands:
    - pip check
  requires:
    - astropy
    - pip
    - xarray

about:
  home: https://github.com/MAVENSDC/cdflib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python CDF reader toolkit
  description: |
    A python CDF reader toolkit
  doc_url: https://cdflib.readthedocs.io/en/latest/
  dev_url: https://github.com/MAVENSDC/cdflib

extra:
  recipe-maintainers:
    - Cadair
    - Alexs12
